### ISSUE TITLE
Sleepmode doesnt work

### ISSUE THREAD

**Issue by Peronia** [Reisyukaku/ReiNX#126]
With reinx 2.2 and 8.0.1 my sleepmode is gone.
In discord im not alone.
When I press power short my switch went black. When I press it again, my switch stay black. Only a hardreset can wake it up.

**Comment by sugeinmy** [comment]
the same

**Comment by jit06** [comment]
The same for me. I was in 6.2 before upgrading...

**Comment by lavaJockey** [comment]
This is fixed in the new commit. If you like using builds it will fix the problem.

**Comment by Peronia** [comment]
I would test it but I cant compile it

**Comment by jit06** [comment]
I just built it with docker, replaced the files on the SDcard and used the new Reinx.bin to boot. But I still get the same symptoms : if I switch push the power button while on, the console never wake up.

**Comment by Reisyukaku** [comment]
fixed and released a hotpatch for it
